apiVersion: compliance.openshift.io/v1alpha1
description: |-
  Ensure Eviction threshold Settings Are Set - evictionSoft: memory.available
  Garbage collection is important to ensure sufficient resource availability
  and avoiding degraded performance and availability. In the worst case, the
  system might crash or just be unusable for a long period of time.
  Based on your system resources and tests, choose an appropriate threshold
  value to activate garbage collection.
id: xccdf_org.ssgproject.content_rule_kubelet_eviction_thresholds_set_soft_memory_available
instructions: |-
  Run the following command on the kubelet node(s):
  $ oc debug -q node/$NODE -- jq -r '.evictionSoft."memory.available"' /host/etc/kubernetes/kubelet.conf
  and make sure it outputs a value.
kind: ComplianceCheckResult
metadata:
  annotations:
    compliance.openshift.io/rule: kubelet-eviction-thresholds-set-soft-memory-available
  creationTimestamp: "2022-05-12T07:53:02Z"
  generation: 1
  labels:
    compliance.openshift.io/automated-remediation: ""
    compliance.openshift.io/check-severity: medium
    compliance.openshift.io/check-status: PASS
    compliance.openshift.io/scan-name: ocp4-cis-node-master
    compliance.openshift.io/suite: cis-compliance
  name: ocp4-cis-node-master-kubelet-eviction-thresholds-set-soft-memory-available
  namespace: openshift-compliance
  ownerReferences:
  - apiVersion: compliance.openshift.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ComplianceScan
    name: ocp4-cis-node-master
    uid: 2f970e1a-c8a8-4424-9fcd-f25a64dc527b
  resourceVersion: "443677"
  uid: 32d0ad94-6f75-4846-a5eb-e363d26360a7
severity: medium
status: PASS
